# data_paths.gd
# Shared data directory paths. Access via class_name (not an autoload).
# Directories are generated by the YAML→tres pipeline (dev/tools/yaml_to_tres.py)
# and are gitignored. Run the pipeline on a fresh checkout before opening the
# project in Godot, or registries will be empty and fail validation at boot.
class_name DataPaths
extends RefCounted

## Template starter entity. Replace/extend for your own domain types.
const EXAMPLES_DIR: String = "res://data/tres/examples"
